const fs = require("fs");

const tealStyle = `*{box-sizing:border-box;margin:0;padding:0}body{font-family:Georgia,'Times New Roman',serif;background:#f8f9fa;color:#1a1a2e;line-height:1.8}.wrapper{max-width:860px;margin:0 auto;background:#fff;padding:60px 72px;min-height:100vh}.course-tag{font-family:Arial,sans-serif;font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:.15em;color:#0f766e;margin-bottom:12px}h1{font-size:2rem;font-weight:700;color:#0f172a;margin-bottom:8px;line-height:1.3}.subtitle{font-size:1.05rem;color:#64748b;margin-bottom:40px;font-style:italic}hr{border:none;border-top:2px solid #99f6e4;margin:32px 0}h2{font-size:1.35rem;font-weight:700;color:#1e293b;margin:36px 0 16px}h3{font-size:1.1rem;font-weight:700;color:#0f766e;margin:24px 0 10px}p{margin-bottom:16px;font-size:1rem}ul,ol{margin:16px 0 16px 24px}li{margin-bottom:8px;font-size:1rem}.highlight-box{background:#f0fdfa;border-left:4px solid #14b8a6;padding:20px 24px;border-radius:0 8px 8px 0;margin:24px 0}.example{background:#f1f5f9;border:1px solid #e2e8f0;border-radius:8px;padding:20px 24px;margin:20px 0}table{width:100%;border-collapse:collapse;margin:24px 0;font-size:.95rem}th{background:#0f766e;color:#fff;padding:12px 16px;text-align:left;font-family:Arial,sans-serif;font-weight:600}td{padding:11px 16px;border-bottom:1px solid #e2e8f0}tr:nth-child(even) td{background:#f0fdfa}.summary{background:#0f172a;color:#e2e8f0;border-radius:12px;padding:28px 32px;margin:40px 0 0}.summary h2{color:#2dd4bf;margin-top:0}.summary li{color:#cbd5e1}@media(max-width:640px){.wrapper{padding:32px 24px}h1{font-size:1.5rem}}`;

function makeHTML(style, tag, title, subtitle, body, quizData) {
  return `<!DOCTYPE html>\n<html lang="es">\n<head>\n  <meta charset="UTF-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n  <title>${title} | Español Sin Fronteras</title>\n  <style>${style}</style>\n</head>\n<body>\n<div class="wrapper">\n  <div class="course-tag">${tag}</div>\n  <h1>${title}</h1>\n  <p class="subtitle">${subtitle}</p>\n  <hr>\n${body}\n</div>\n<script>\nwindow.QUIZ_DATA = ${JSON.stringify(quizData, null, 2)};\n</script>\n<script src="quiz-engine.js"></script>\n</body>\n</html>`;
}

const caps = [
  { n:11, title:"El Mercado Laboral y los Salarios", sub:"Cómo se determinan los salarios, el papel de los sindicatos, el salario mínimo y las tendencias del empleo en el siglo XXI.",
    body:`<h2>¿Cómo se Fijan los Salarios?</h2><p>En una economía de mercado, los salarios se determinan por la <strong>oferta y demanda de trabajo</strong>. Si hay pocos trabajadores con una habilidad específica y muchas empresas la necesitan, el salario sube.</p><div class="highlight-box"><strong>Capital humano:</strong> La educación, la experiencia y las habilidades aumentan la productividad del trabajador y, por tanto, su salario potencial.</div><h2>Tipos de Desempleo</h2><table><tr><th>Tipo</th><th>Descripción</th></tr><tr><td>Friccional</td><td>Transición entre empleos; siempre existirá</td></tr><tr><td>Estructural</td><td>Falta de coincidencia entre habilidades y empleos disponibles</td></tr><tr><td>Cíclico</td><td>Causado por recesiones económicas</td></tr><tr><td>Estacional</td><td>Variaciones según la época del año</td></tr></table><h2>El Salario Mínimo</h2><p>El <strong>salario mínimo</strong> es el piso legal por debajo del cual ningún empleador puede pagar. Sus efectos son debatidos: puede reducir la pobreza pero también puede reducir el empleo si está muy por encima del salario de equilibrio.</p><div class="example"><strong>Dato 2026:</strong> El salario mínimo federal de EE.UU. es $7.25/hora desde 2009, pero muchos estados tienen salarios mínimos más altos (California: $16/hora).</div><h2>Sindicatos y Negociación Colectiva</h2><p>Los <strong>sindicatos</strong> negocian colectivamente en nombre de los trabajadores para obtener mejores salarios, beneficios y condiciones laborales. La afiliación sindical en EE.UU. ha caído del 35% (1950s) al ~10% actual.</p><h2>El Futuro del Trabajo</h2><p>La automatización y la inteligencia artificial están transformando el mercado laboral. Trabajos rutinarios están siendo automatizados; aumenta la demanda de habilidades cognitivas, creativas y sociales.</p><div class="summary"><h2>Resumen del Capítulo 11</h2><ul><li>Los salarios se determinan por oferta y demanda de trabajo</li><li>El capital humano (educación, experiencia) eleva el salario potencial</li><li>4 tipos de desempleo: friccional, estructural, cíclico, estacional</li><li>El salario mínimo es el piso legal de remuneración</li><li>La IA está transformando el mercado laboral del siglo XXI</li></ul></div>`,
    quiz:{lang:"es",questions:[
      {q:"¿Qué determina los salarios en una economía de mercado?",options:["El gobierno exclusivamente","La oferta y demanda de trabajo","Las tradiciones históricas","El tamaño de la empresa"],answer:1},
      {q:"¿Qué es el capital humano?",options:["El dinero en efectivo de una empresa","Educación, experiencia y habilidades del trabajador","Los activos físicos de una fábrica","El capital de riesgo"],answer:1},
      {q:"El desempleo cíclico es causado por:",options:["Cambio de empleo voluntario","Falta de habilidades","Recesiones económicas","Variaciones estacionales"],answer:2},
      {q:"¿Cuál es el salario mínimo federal de EE.UU. en 2026?",options:["$5.15/hora","$7.25/hora","$10/hora","$15/hora"],answer:1},
      {q:"Los sindicatos se encargan de:",options:["Establecer el salario mínimo","Negociar colectivamente por mejores condiciones laborales","Contratar trabajadores","Reducir impuestos"],answer:1},
      {q:"El desempleo friccional es:",options:["Causado por recesiones","La transición normal entre empleos","Provocado por la automatización","Un problema estructural grave"],answer:1},
      {q:"¿Qué tendencia ha tenido la afiliación sindical en EE.UU.?",options:["Ha aumentado al 50%","Se mantiene estable en 35%","Ha caído al ~10%","Ha desaparecido completamente"],answer:2},
      {q:"¿Qué tipo de habilidades demanda más el mercado laboral del siglo XXI?",options:["Habilidades rutinarias manuales","Cognitivas, creativas y sociales","Solo técnicas","Solo físicas"],answer:1},
      {q:"El desempleo estructural ocurre cuando:",options:["La economía entra en recesión","No hay coincidencia entre habilidades y empleos disponibles","Las personas cambian voluntariamente de trabajo","La demanda cae en verano"],answer:1},
      {q:"¿Cuál es el salario mínimo en California en 2026?",options:["$7.25/hora","$12/hora","$16/hora","$20/hora"],answer:2},
    ]}
  },
  { n:12, title:"La Globalización y sus Efectos", sub:"Cómo la integración económica mundial transforma el comercio, el trabajo, la cultura y la desigualdad entre naciones.",
    body:`<h2>¿Qué es la Globalización?</h2><p>La <strong>globalización</strong> es el proceso de integración creciente de las economías, culturas y poblaciones del mundo a través del comercio, la inversión, la tecnología y la migración.</p><div class="highlight-box"><strong>Dato:</strong> El comercio mundial representaba el 5% del PIB global en 1913. Hoy supera el 60%. La globalización se aceleró drásticamente tras la Segunda Guerra Mundial.</div><h2>Ventajas de la Globalización</h2><ul><li>Reducción de precios para los consumidores (producción en países de bajo costo)</li><li>Acceso a mercados más grandes para exportadores</li><li>Difusión de tecnología e innovación</li><li>Reducción de la pobreza extrema (500 millones salieron de la pobreza en China 1990-2010)</li><li>Mayor variedad de productos disponibles</li></ul><h2>Desventajas y Críticas</h2><ul><li>Pérdida de empleos manufactureros en países desarrollados</li><li>Aumento de la desigualdad dentro de países ricos</li><li>Dependencia de cadenas de suministro vulnerables (COVID-19 lo demostró)</li><li>Homogeneización cultural (pérdida de diversidad local)</li><li>Carrera hacia el fondo en estándares laborales y ambientales</li></ul><div class="example"><strong>Ejemplo:</strong> Un iPhone se diseña en EE.UU., usa chips de Taiwán, pantallas de Corea del Sur, y se ensambla en China. Es el producto arquetípico de la globalización.</div><h2>Desglobalización y Reshoring</h2><p>Desde 2018 (guerra comercial EE.UU.-China) y COVID-19 (2020), hay una tendencia al <strong>reshoring</strong> (traer producción de vuelta) y "friend-shoring" (solo con países aliados) para reducir vulnerabilidades.</p><div class="summary"><h2>Resumen del Capítulo 12</h2><ul><li>La globalización integra economías vía comercio, inversión y tecnología</li><li>El comercio mundial superó el 60% del PIB global</li><li>Ventajas: precios bajos, tecnología, reducción de pobreza</li><li>Desventajas: pérdida de empleos locales, desigualdad, dependencia</li><li>COVID-19 y tensiones geopolíticas impulsan el reshoring</li></ul></div>`,
    quiz:{lang:"es",questions:[
      {q:"¿Qué porcentaje del PIB global representa el comercio mundial hoy?",options:["5%","20%","40%","Más del 60%"],answer:3},
      {q:"¿Cuánto representaba el comercio mundial en 1913?",options:["1%","5%","20%","40%"],answer:1},
      {q:"¿Cuántas personas salieron de la pobreza en China entre 1990-2010?",options:["50 millones","200 millones","500 millones","1,000 millones"],answer:2},
      {q:"¿Qué demostró el COVID-19 sobre la globalización?",options:["Que es perfectamente eficiente","La vulnerabilidad de las cadenas de suministro globales","Que el comercio mundial no importa","Que los precios siempre bajan"],answer:1},
      {q:"¿Qué es el reshoring?",options:["Exportar más productos","Traer la producción de vuelta al país de origen","Abrir nuevos mercados","Reducir aranceles"],answer:1},
      {q:"Una crítica a la globalización es:",options:["Que reduce los precios para consumidores","La pérdida de empleos manufactureros en países ricos","El exceso de tecnología","La abundancia de productos"],answer:1},
      {q:"¿Cuál es el producto arquetípico de la globalización según el texto?",options:["Un auto alemán","Un iPhone","Una bolsa Louis Vuitton","Un televisor japonés"],answer:1},
      {q:"La 'carrera hacia el fondo' en globalización se refiere a:",options:["Precios que bajan constantemente","Reducción de estándares laborales y ambientales para competir","La caída del PIB global","La migración laboral"],answer:1},
      {q:"¿Qué inició la tendencia hacia la desglobalización desde 2018?",options:["La crisis financiera de 2008","La pandemia de COVID-19","La guerra comercial EE.UU.-China","La creación de la OMC"],answer:2},
      {q:"¿Cuál es una ventaja directa de la globalización para el consumidor?",options:["Más empleos locales","Precios más bajos por producción en países de bajo costo","Menos productos disponibles","Mayor protección arancelaria"],answer:1},
    ]}
  },
  { n:13, title:"La Deuda Pública", sub:"Qué es la deuda soberana, cómo se financia el gobierno, el debate déficit vs. superávit y los riesgos de un endeudamiento excesivo.",
    body:`<h2>¿Qué es la Deuda Pública?</h2><p>La <strong>deuda pública</strong> es el total de dinero que un gobierno debe a sus acreedores. Se genera cuando el gobierno gasta más de lo que recauda en impuestos (<strong>déficit fiscal</strong>). El gobierno financia este déficit emitiendo bonos.</p><div class="highlight-box"><strong>Dato 2026:</strong> La deuda pública de EE.UU. supera los $36 billones (trillion en inglés), equivalente al ~124% de su PIB anual.</div><h2>Déficit vs. Superávit Fiscal</h2><table><tr><th>Concepto</th><th>Definición</th><th>Efecto</th></tr><tr><td>Déficit</td><td>Gasto > Ingresos</td><td>Aumenta la deuda</td></tr><tr><td>Superávit</td><td>Ingresos > Gasto</td><td>Reduce la deuda</td></tr><tr><td>Presupuesto equilibrado</td><td>Gasto = Ingresos</td><td>Deuda estable</td></tr></table><h2>¿Es Mala la Deuda Pública?</h2><p>Los economistas están divididos. <strong>Keynesianos</strong>: La deuda pública en recesiones estimula la economía (multiplicador keynesiano). <strong>Austeristas</strong>: La deuda excesiva frena el crecimiento y genera riesgo de impago.</p><div class="example"><strong>Casos extremos:</strong> Japón tiene una deuda del 260% del PIB pero mantiene tasas bajas porque la mayor parte la tienen ciudadanos japoneses. Argentina ha incumplido su deuda 9 veces.</div><h2>La Deuda y las Generaciones Futuras</h2><p>La deuda pública se pagará con impuestos futuros, lo que representa una carga para generaciones que no participaron en las decisiones de gasto. Sin embargo, la deuda invertida en infraestructura o educación puede generar beneficios que justifican ese costo.</p><h2>Calificadoras de Riesgo</h2><p>Agencias como <strong>Moody's, S&P y Fitch</strong> califican la capacidad de pago de los países. Una rebaja de calificación (downgrade) eleva las tasas de interés que el país debe pagar.</p><div class="summary"><h2>Resumen del Capítulo 13</h2><ul><li>La deuda pública surge de déficits fiscales acumulados</li><li>EE.UU. supera $36 billones de deuda (~124% del PIB)</li><li>Déficit = gasto mayor que ingresos; superávit = ingresos mayores que gasto</li><li>Los economistas debaten si la deuda pública es dañina o necesaria</li><li>S&P, Moody's y Fitch califican la solvencia de los países</li></ul></div>`,
    quiz:{lang:"es",questions:[
      {q:"¿Qué genera la deuda pública?",options:["Superávits fiscales","Déficits fiscales acumulados","Las exportaciones","Las reservas de oro"],answer:1},
      {q:"¿Cuánto supera la deuda pública de EE.UU. en 2026?",options:["$10 billones","$20 billones","$36 billones","$50 billones"],answer:2},
      {q:"¿Qué es un déficit fiscal?",options:["Cuando los ingresos superan el gasto","Cuando el gasto supera los ingresos","Cuando el presupuesto está equilibrado","Cuando bajan los impuestos"],answer:1},
      {q:"¿Qué país tiene una deuda del 260% del PIB pero la mantiene estable?",options:["Argentina","Grecia","Japón","Italia"],answer:2},
      {q:"¿Cuántas veces ha incumplido su deuda Argentina?",options:["2","5","9","15"],answer:2},
      {q:"¿Qué hacen las calificadoras de riesgo como S&P?",options:["Establecen el salario mínimo","Califican la capacidad de pago de los países","Fijan los tipos de cambio","Emiten bonos del gobierno"],answer:1},
      {q:"Un 'downgrade' de calificación crediticia provoca:",options:["Tasas de interés más bajas","Tasas de interés más altas","Reducción de la deuda","Mayor confianza del mercado"],answer:1},
      {q:"Los keynesianos defienden que la deuda pública en recesiones:",options:["Siempre es dañina","Estimula la economía","Debe eliminarse inmediatamente","No tiene ningún efecto"],answer:1},
      {q:"¿Cómo financia el gobierno un déficit fiscal?",options:["Imprimiendo dinero ilimitadamente","Emitiendo bonos del gobierno","Subiendo los salarios públicos","Reduciendo la deuda anterior"],answer:1},
      {q:"¿Cuál NO es una calificadora de riesgo soberano?",options:["Moody's","S&P","Fitch","Bloomberg"],answer:3},
    ]}
  },
  { n:14, title:"Los Ciclos Económicos", sub:"Las fases de expansión, auge, recesión y recuperación que caracterizan el comportamiento de todas las economías a lo largo del tiempo.",
    body:`<h2>¿Qué es un Ciclo Económico?</h2><p>El <strong>ciclo económico</strong> describe las fluctuaciones periódicas en la actividad económica de un país. Ninguna economía crece de forma constante — alterna fases de expansión y contracción.</p><div class="highlight-box"><strong>Definición técnica de recesión:</strong> Dos trimestres consecutivos de crecimiento negativo del PIB. Una depresión es una recesión severa y prolongada (como la Gran Depresión de 1929-1939).</div><h2>Las 4 Fases del Ciclo</h2><table><tr><th>Fase</th><th>Características</th></tr><tr><td>Expansión</td><td>PIB sube, empleo aumenta, confianza alta, precios suben moderadamente</td></tr><tr><td>Auge (Peak)</td><td>Máximo de actividad; inflación alta, pleno empleo, posible sobrecalentamiento</td></tr><tr><td>Recesión (Contracción)</td><td>PIB cae, desempleo sube, confianza baja, precios se estabilizan</td></tr><tr><td>Recuperación (Trough)</td><td>Mínimo alcanzado; la economía empieza a crecer de nuevo</td></tr></table><h2>Indicadores del Ciclo Económico</h2><ul><li><strong>Indicadores adelantados</strong>: Predicen el ciclo (bolsa de valores, permisos de construcción, pedidos de manufactura)</li><li><strong>Indicadores coincidentes</strong>: Confirman la fase actual (PIB, empleo, ventas)</li><li><strong>Indicadores rezagados</strong>: Confirman después del hecho (tasa de desempleo, crédito)</li></ul><div class="example"><strong>La Gran Recesión (2008-2009):</strong> Causada por la crisis hipotecaria de EE.UU., se propagó globalmente. El PIB de EE.UU. cayó 4.3% y el desempleo llegó al 10%.</div><h2>Política Anticíclica</h2><p>Los gobiernos usan política fiscal (cambios en gasto e impuestos) y los bancos centrales usan política monetaria (tasas de interés) para suavizar los ciclos económicos.</p><div class="summary"><h2>Resumen del Capítulo 14</h2><ul><li>El ciclo económico tiene 4 fases: expansión, auge, recesión, recuperación</li><li>Recesión técnica = 2 trimestres consecutivos de PIB negativo</li><li>Los indicadores adelantados predicen; los coincidentes confirman; los rezagados verifican</li><li>La Gran Recesión (2008-2009) redujo el PIB de EE.UU. 4.3%</li><li>Políticas fiscal y monetaria buscan suavizar los ciclos</li></ul></div>`,
    quiz:{lang:"es",questions:[
      {q:"¿Cuál es la definición técnica de recesión?",options:["Un mes de PIB negativo","Dos trimestres consecutivos de PIB negativo","Un año de desempleo alto","Inflación superior al 10%"],answer:1},
      {q:"¿Cuál es el orden correcto de las fases del ciclo económico?",options:["Recesión, auge, expansión, recuperación","Expansión, auge, recesión, recuperación","Auge, expansión, recuperación, recesión","Recuperación, recesión, auge, expansión"],answer:1},
      {q:"Durante la fase de auge (peak), ¿qué caracteriza a la economía?",options:["Alto desempleo y baja inflación","Bajo PIB y confianza mínima","Pleno empleo e inflación alta","Recesión inminente sin señales"],answer:2},
      {q:"¿Qué son los indicadores adelantados?",options:["Los que confirman lo ocurrido","Los que predicen el ciclo futuro","Los que miden el ciclo actual","Los que miden el desempleo rezagado"],answer:1},
      {q:"¿Cuánto cayó el PIB de EE.UU. durante la Gran Recesión?",options:["1.2%","2.5%","4.3%","8%"],answer:2},
      {q:"¿A qué llegó el desempleo en EE.UU. durante la Gran Recesión?",options:["5%","7%","10%","15%"],answer:2},
      {q:"Los permisos de construcción son un indicador:",options:["Rezagado","Coincidente","Adelantado","No relevante"],answer:2},
      {q:"¿Qué es una depresión económica?",options:["Una recesión de un mes","Una recesión severa y prolongada","Una caída de la bolsa de valores","Un período de inflación alta"],answer:1},
      {q:"La política monetaria anticíclica es implementada por:",options:["El gobierno central","El Congreso","Los bancos centrales","Las empresas privadas"],answer:2},
      {q:"La tasa de desempleo es un indicador:",options:["Adelantado","Coincidente","Rezagado","Predictivo"],answer:2},
    ]}
  },
  { n:15, title:"El Papel del Estado en la Economía", sub:"Las distintas visiones sobre cuánto debe intervenir el gobierno en la economía: desde el laissez-faire hasta la planificación central.",
    body:`<h2>¿Por Qué Interviene el Estado?</h2><p>Incluso las economías más libres tienen intervención estatal para corregir los <strong>fallos del mercado</strong>: situaciones donde el mercado libre no produce resultados óptimos.</p><div class="highlight-box"><strong>Fallos del mercado:</strong> Bienes públicos (defensa, calles), externalidades (contaminación), monopolios, información asimétrica (seguros de salud) y bienes meritorios (educación).</div><h2>Funciones Económicas del Estado</h2><table><tr><th>Función</th><th>Ejemplo</th></tr><tr><td>Provisión de bienes públicos</td><td>Defensa nacional, alumbrado público, carreteras</td></tr><tr><td>Regulación</td><td>Leyes antimonopolio, normas de seguridad alimentaria</td></tr><tr><td>Redistribución</td><td>Impuestos progresivos, programas sociales (Medicare, Medicaid)</td></tr><tr><td>Estabilización</td><td>Política fiscal y monetaria para suavizar ciclos</td></tr><tr><td>Corrección de externalidades</td><td>Impuestos al carbono, subsidios a energías renovables</td></tr></table><h2>Espectro Ideológico</h2><ul><li><strong>Laissez-faire</strong>: Mínima intervención estatal; el mercado se autorregula (Adam Smith)</li><li><strong>Economía mixta</strong>: Mercado libre con regulación y programas sociales (mayoría de democracias)</li><li><strong>Socialismo democrático</strong>: Estado controla sectores clave (salud, educación)</li><li><strong>Economía planificada</strong>: El Estado controla toda la producción (URSS, Cuba)</li></ul><div class="example"><strong>Externalidad negativa:</strong> Una fábrica que contamina un río impone costos a la sociedad que no paga. El Estado puede cobrar un impuesto igual al daño causado (impuesto pigouviano).</div><div class="summary"><h2>Resumen del Capítulo 15</h2><ul><li>El Estado interviene para corregir fallos del mercado</li><li>Fallos: bienes públicos, externalidades, monopolios, información asimétrica</li><li>Funciones: provisión, regulación, redistribución, estabilización</li><li>El espectro va del laissez-faire al socialismo</li><li>La mayoría de economías modernas son economías mixtas</li></ul></div>`,
    quiz:{lang:"es",questions:[
      {q:"¿Qué es un fallo del mercado?",options:["Cuando la bolsa cae","Cuando el mercado libre no produce resultados óptimos","Cuando bajan los precios","Cuando sube el desempleo"],answer:1},
      {q:"¿Cuál es un ejemplo de bien público?",options:["Un automóvil","Un restaurante","La defensa nacional","Una tienda de ropa"],answer:2},
      {q:"¿Qué son las externalidades?",options:["Comercio internacional","Costos o beneficios que recaen en terceros no involucrados en la transacción","Los impuestos externos","Los aranceles de importación"],answer:1},
      {q:"¿Qué propone el enfoque laissez-faire?",options:["Estado que controla toda la producción","Mínima intervención estatal; el mercado se autorregula","Impuestos altos para redistribuir","Nacionalización de empresas"],answer:1},
      {q:"¿Qué tipo de economía tiene la mayoría de las democracias modernas?",options:["Economía planificada","Laissez-faire puro","Economía mixta","Socialismo total"],answer:2},
      {q:"¿Qué es un impuesto pigouviano?",options:["Un impuesto al comercio exterior","Un impuesto igual al daño causado por una externalidad negativa","Un impuesto a las ganancias de capital","Un impuesto al lujo"],answer:1},
      {q:"¿Cuál es un ejemplo de información asimétrica como fallo del mercado?",options:["La contaminación industrial","Los seguros de salud","Los bienes públicos","El monopolio de Microsoft"],answer:1},
      {q:"La redistribución estatal incluye:",options:["Subsidios a la defensa","Impuestos progresivos y programas sociales","Regulación de monopolios","Política monetaria"],answer:1},
      {q:"En una economía planificada (como la URSS):",options:["El mercado fija todos los precios","El Estado controla toda la producción","Las empresas privadas dominan","No hay intervención estatal"],answer:1},
      {q:"¿Quién es el padre intelectual del laissez-faire?",options:["Karl Marx","John Maynard Keynes","Adam Smith","Milton Friedman"],answer:2},
    ]}
  },
  { n:16, title:"Las Crisis Económicas: Causas y Soluciones", sub:"Anatomía de las grandes crisis económicas de la historia: qué las causa, cómo se propagan y qué políticas ayudan a superarlas.",
    body:`<h2>¿Qué Causa una Crisis Económica?</h2><p>Las crisis económicas suelen tener múltiples causas que se retroalimentan. Los economistas identifican patrones comunes: burbujas especulativas, exceso de deuda, shocks externos y fallas de regulación.</p><div class="highlight-box"><strong>El ciclo de las burbujas:</strong> Optimismo excesivo → precios suben → más especuladores entran → precios se desconectan del valor real → catalizador desencadena el pánico → burbuja estalla.</div><h2>Crisis Económicas Históricas</h2><table><tr><th>Crisis</th><th>Causa Principal</th><th>Impacto</th></tr><tr><td>Gran Depresión (1929)</td><td>Colapso bursátil + deflación + proteccionismo</td><td>PIB EE.UU. -30%, desempleo 25%</td></tr><tr><td>Crisis del Petróleo (1973)</td><td>Embargo de la OPEP, stagflación</td><td>Inflación + recesión simultáneas</td></tr><tr><td>Crisis Asiática (1997)</td><td>Tipos de cambio fijos + fuga de capitales</td><td>Colapso de monedas en SE Asia</td></tr><tr><td>Gran Recesión (2008)</td><td>Burbuja hipotecaria subprime</td><td>Crisis bancaria global</td></tr><tr><td>COVID-19 (2020)</td><td>Shock externo: pandemia</td><td>PIB mundial -3.5% en 2020</td></tr></table><h2>Propagación de las Crisis</h2><p>Las crisis se propagan a través del <strong>sistema financiero interconectado</strong>: un banco que falla puede arrastrar a otros (efecto dominó). La globalización acelera la propagación entre países.</p><div class="example"><strong>Lehman Brothers (2008):</strong> La quiebra de este banco de inversión congeló los mercados de crédito mundiales en cuestión de días. El crédito interbancario casi desapareció.</div><h2>Soluciones a las Crisis</h2><ul><li><strong>Política monetaria expansiva</strong>: Bajar tasas de interés, QE (compra de activos)</li><li><strong>Política fiscal expansiva</strong>: Estímulos económicos, extensión del desempleo</li><li><strong>Rescates bancarios</strong>: Evitar el colapso del sistema financiero</li><li><strong>Regulación post-crisis</strong>: Dodd-Frank (2010) tras la crisis de 2008</li></ul><div class="summary"><h2>Resumen del Capítulo 16</h2><ul><li>Las crisis surgen de burbujas, exceso de deuda, shocks externos y fallos regulatorios</li><li>La Gran Depresión (1929) fue la peor del siglo XX: -30% PIB, 25% desempleo</li><li>La Gran Recesión (2008) fue causada por la burbuja hipotecaria subprime</li><li>Las crisis se propagan por el sistema financiero interconectado</li><li>Respuestas: política monetaria y fiscal expansiva + regulación más estricta</li></ul></div>`,
    quiz:{lang:"es",questions:[
      {q:"¿Cuál fue el desempleo máximo en EE.UU. durante la Gran Depresión?",options:["10%","15%","25%","40%"],answer:2},
      {q:"¿Qué causó la Crisis del Petróleo de 1973?",options:["Quiebra de bancos","Embargo de la OPEP","Burbuja inmobiliaria","Guerra comercial"],answer:1},
      {q:"¿Qué banco detonó la crisis global en 2008?",options:["Goldman Sachs","JP Morgan","Lehman Brothers","Citigroup"],answer:2},
      {q:"¿Cuánto cayó el PIB mundial en 2020 por la pandemia?",options:["-1%","-3.5%","-7%","-10%"],answer:1},
      {q:"¿Qué es la 'stagflación'?",options:["Crecimiento alto con inflación baja","Inflación y recesión simultáneas","Deflación y auge económico","Desempleo con superávit fiscal"],answer:1},
      {q:"¿Qué ley reguló el sistema financiero de EE.UU. tras la crisis de 2008?",options:["Glass-Steagall","Dodd-Frank","Sarbanes-Oxley","Sherman Act"],answer:1},
      {q:"¿Qué es el 'QE' (Quantitative Easing)?",options:["Subir tasas de interés","Compra de activos por el banco central para inyectar liquidez","Reducción del gasto fiscal","Aumento de impuestos"],answer:1},
      {q:"¿Cuánto cayó el PIB de EE.UU. durante la Gran Depresión?",options:["-10%","-20%","-30%","-50%"],answer:2},
      {q:"¿Por qué se propagan rápidamente las crisis en la era moderna?",options:["Por la inflación global","Por el sistema financiero interconectado y la globalización","Por las guerras comerciales","Por la política fiscal expansiva"],answer:1},
      {q:"¿Qué detonó la Gran Recesión de 2008?",options:["Altos precios del petróleo","Crisis de deuda soberana","Burbuja hipotecaria subprime","Colapso del comercio internacional"],answer:2},
    ]}
  },
  { n:17, title:"Economía Digital e Innovación", sub:"Cómo internet, los datos, las plataformas y la inteligencia artificial están creando nuevas formas de valor económico y transformando industrias.",
    body:`<h2>La Nueva Economía Digital</h2><p>La <strong>economía digital</strong> es el conjunto de actividades económicas impulsadas por tecnologías digitales: internet, datos, software, computación en la nube e inteligencia artificial. Ya representa más del 15% del PIB mundial.</p><div class="highlight-box"><strong>Dato:</strong> Las 5 empresas más valiosas del mundo en 2026 son todas tecnológicas: Apple, Microsoft, Nvidia, Alphabet (Google) y Amazon. Su valor combinado supera los $15 billones.</div><h2>Características de la Economía Digital</h2><table><tr><th>Característica</th><th>Descripción</th></tr><tr><td>Costos marginales cercanos a cero</td><td>Copiar software o música no cuesta casi nada</td></tr><tr><td>Efectos de red</td><td>El valor del producto aumenta con más usuarios (WhatsApp, internet)</td></tr><tr><td>Economías de escala extremas</td><td>Una app puede servir a millones sin costos proporcionales</td></tr><tr><td>Ganador se lleva todo</td><td>Tendencia a monopolios naturales (Google en búsqueda: 90%)</td></tr><tr><td>Datos como activo</td><td>"El dato es el nuevo petróleo" — valor enorme pero invisible</td></tr></table><h2>Plataformas y Mercados de Dos Lados</h2><p>Las plataformas digitales (Uber, Airbnb, Amazon Marketplace) conectan dos grupos de usuarios creando valor para ambos. No producen el bien directamente — son intermediarios tecnológicos.</p><div class="example"><strong>Ejemplo:</strong> Airbnb tiene más habitaciones disponibles que las cadenas hoteleras más grandes del mundo, pero no posee ningún hotel. Su activo es la plataforma y la confianza entre usuarios.</div><h2>IA y el Futuro de la Productividad</h2><p>La IA generativa (ChatGPT, Claude, Gemini) promete aumentar la productividad laboral entre un 15% y 40% según McKinsey. También amenaza con automatizar el 30% de las tareas de muchos trabajos de oficina.</p><div class="summary"><h2>Resumen del Capítulo 17</h2><ul><li>La economía digital representa más del 15% del PIB mundial</li><li>Las 5 empresas más valiosas del mundo son tecnológicas</li><li>Características: costos marginales casi cero, efectos de red, ganador se lleva todo</li><li>Las plataformas son intermediarios sin activos físicos propios</li><li>La IA promete aumentar la productividad entre 15% y 40%</li></ul></div>`,
    quiz:{lang:"es",questions:[
      {q:"¿Qué porcentaje del PIB mundial representa la economía digital en 2026?",options:["5%","10%","Más del 15%","30%"],answer:2},
      {q:"¿Cuál NO es una de las 5 empresas más valiosas del mundo en 2026?",options:["Apple","Microsoft","Toyota","Nvidia"],answer:2},
      {q:"¿Qué son los 'efectos de red'?",options:["La infraestructura de internet","Que el valor del producto aumenta con más usuarios","La velocidad de las redes 5G","Los costos de conectividad"],answer:1},
      {q:"La tendencia 'ganador se lleva todo' en digital se refiere a:",options:["Competencia perfecta","Tendencia a monopolios naturales","Igual distribución de mercado","Muchas pequeñas empresas compitiendo"],answer:1},
      {q:"¿Qué comparte Airbnb con otras plataformas digitales?",options:["Posee muchos hoteles","No produce el bien directamente; es intermediario tecnológico","Tiene los costos más bajos del sector","Es la empresa más antigua del sector"],answer:1},
      {q:"¿Qué cuota de mercado tiene Google en búsquedas?",options:["50%","70%","90%","100%"],answer:2},
      {q:"Según McKinsey, ¿cuánto puede aumentar la IA la productividad laboral?",options:["5-10%","15-40%","50-70%","100%"],answer:1},
      {q:"¿Qué significa que el dato 'es el nuevo petróleo'?",options:["Los datos son físicos como el petróleo","Los datos tienen un valor económico enorme","Los datos se agotan","Los datos contaminan"],answer:1},
      {q:"¿Cuál es la característica 'costos marginales cercanos a cero' en la economía digital?",options:["Producir una unidad adicional de software casi no cuesta nada","Los salarios de los programadores son bajos","Las empresas no pagan impuestos","La energía eléctrica es gratuita"],answer:0},
      {q:"Uber y Airbnb son ejemplos de:",options:["Fabricantes directos","Plataformas de mercados de dos lados","Monopolios estatales","Cooperativas de trabajadores"],answer:1},
    ]}
  },
  { n:18, title:"Desigualdad Económica", sub:"Las causas y consecuencias de la brecha entre ricos y pobres, cómo se mide y qué políticas buscan reducirla.",
    body:`<h2>¿Cómo Se Mide la Desigualdad?</h2><p>El indicador más usado es el <strong>Coeficiente de Gini</strong>: va de 0 (igualdad perfecta: todos ganan lo mismo) a 1 (desigualdad máxima: una persona tiene todo). También se usa la comparación del ingreso del 10% más rico vs. el 10% más pobre.</p><div class="highlight-box"><strong>Dato global 2026:</strong> El 1% más rico del mundo posee más del 45% de la riqueza total. Las 10 personas más ricas tienen más riqueza que los 3,100 millones más pobres combinados.</div><h2>Causas de la Desigualdad</h2><ul><li><strong>Globalización</strong>: Beneficia más a trabajadores calificados y dueños de capital</li><li><strong>Tecnología</strong>: Reemplaza trabajos de rutina; premia habilidades cognitivas</li><li><strong>Educación</strong>: Acceso desigual perpetúa la brecha intergeneracional</li><li><strong>Herencia</strong>: La riqueza acumulada se transfiere entre generaciones</li><li><strong>Discriminación</strong>: Género, raza y origen afectan salarios y oportunidades</li></ul><h2>Consecuencias de la Alta Desigualdad</h2><table><tr><th>Área</th><th>Impacto</th></tr><tr><td>Económica</td><td>Menor consumo agregado, menor movilidad social, menor crecimiento</td></tr><tr><td>Social</td><td>Mayor criminalidad, peor salud pública, menor confianza social</td></tr><tr><td>Política</td><td>Captura del Estado por élites, erosión democrática</td></tr></table><div class="example"><strong>La Curva de Kuznets:</strong> Históricamente, la desigualdad aumenta durante la industrialización y luego baja cuando el país se vuelve más rico. Este patrón no siempre se cumple en la era digital.</div><h2>Políticas para Reducir la Desigualdad</h2><ul><li>Impuestos progresivos (los más ricos pagan mayor porcentaje)</li><li>Impuesto a la riqueza y herencias</li><li>Inversión en educación pública de calidad</li><li>Salario mínimo y transferencias sociales</li><li>Renta básica universal (debatida)</li></ul><div class="summary"><h2>Resumen del Capítulo 18</h2><ul><li>Coeficiente de Gini: 0 = igualdad perfecta, 1 = desigualdad máxima</li><li>El 1% más rico posee más del 45% de la riqueza mundial</li><li>Causas: tecnología, globalización, educación desigual, herencia</li><li>Alta desigualdad frena el crecimiento y erosiona la democracia</li><li>Políticas: impuestos progresivos, educación, transferencias sociales</li></ul></div>`,
    quiz:{lang:"es",questions:[
      {q:"¿Qué mide el Coeficiente de Gini?",options:["El PIB per cápita","El nivel de desigualdad económica (0=igual, 1=máxima desigualdad)","La inflación","El desempleo"],answer:1},
      {q:"¿Qué porcentaje de la riqueza mundial posee el 1% más rico?",options:["20%","30%","Más del 45%","60%"],answer:2},
      {q:"¿Cuál es una consecuencia económica de la alta desigualdad?",options:["Mayor consumo agregado","Menor movilidad social y menor crecimiento","Más innovación tecnológica","Menor deuda pública"],answer:1},
      {q:"¿Qué tipo de impuesto ayuda a reducir la desigualdad?",options:["Impuesto regresivo","IVA uniforme","Impuesto progresivo (más ricos pagan más %)","Impuesto al consumo"],answer:2},
      {q:"La Curva de Kuznets predice que la desigualdad:",options:["Siempre aumenta con el desarrollo","Aumenta durante la industrialización y luego baja","Siempre baja con el crecimiento","No tiene relación con el desarrollo"],answer:1},
      {q:"¿Cuál NO es una causa de desigualdad según el texto?",options:["Globalización","Herencia de riqueza","Acceso desigual a educación","Mayor regulación bancaria"],answer:3},
      {q:"¿Qué impacto político tiene la alta desigualdad?",options:["Mayor participación ciudadana","Captura del Estado por élites y erosión democrática","Más transparencia gubernamental","Mejor representación política"],answer:1},
      {q:"La renta básica universal es:",options:["Un impuesto nuevo","Un salario mínimo más alto","Un ingreso incondicional para todos los ciudadanos (debatida)","Un bono para desempleados"],answer:2},
      {q:"¿Qué factor tecnológico aumenta la desigualdad?",options:["Mayor acceso a internet","Reemplazo de trabajos rutinarios y premio a habilidades cognitivas","Precios bajos de smartphones","Redes sociales gratuitas"],answer:1},
      {q:"¿Cuánto del PIB consume en promedio el 10% más rico vs el 10% más pobre en países con alta desigualdad?",options:["El doble","El triple","Más de 10 veces","Exactamente igual"],answer:2},
    ]}
  },
  { n:19, title:"Economía Verde y Sostenibilidad", sub:"El costo económico del cambio climático, los mercados de carbono, la transición energética y las oportunidades de la economía verde.",
    body:`<h2>El Cambio Climático como Problema Económico</h2><p>El <strong>cambio climático</strong> es la mayor externalidad negativa de la historia humana. Los costos de la inacción — daños por eventos extremos, pérdidas agrícolas, migraciones climáticas — superan ampliamente los costos de la transición verde.</p><div class="highlight-box"><strong>Informe Stern (2006):</strong> El costo de no actuar ante el cambio climático podría alcanzar el 20% del PIB mundial. Actuar hoy costaría solo el 1-2% del PIB anual.</div><h2>Instrumentos de Política Climática</h2><table><tr><th>Instrumento</th><th>Descripción</th></tr><tr><td>Impuesto al carbono</td><td>Precio directo a las emisiones de CO₂</td></tr><tr><td>Cap and Trade</td><td>Límite de emisiones + mercado para comprar/vender derechos</td></tr><tr><td>Subsidios verdes</td><td>Apoyo a energías renovables, vehículos eléctricos</td></tr><tr><td>Regulación directa</td><td>Normas de eficiencia energética, prohibición de combustibles fósiles</td></tr></table><h2>La Transición Energética</h2><p>El mundo está transitando de combustibles fósiles (carbón, petróleo, gas) a energías renovables (solar, eólica, hidráulica). En 2025, las energías renovables generaron el 35% de la electricidad mundial, y el costo de la energía solar cayó 90% en una década.</p><div class="example"><strong>Oportunidad económica:</strong> La Agencia Internacional de Energía estima que se necesitan $4 billones anuales en inversión limpia para 2030. Esto crea millones de empleos verdes.</div><h2>Economía Circular</h2><p>La <strong>economía circular</strong> busca eliminar el residuo rediseñando productos para que se reutilicen, reparen y reciclen — en lugar del modelo lineal "fabricar, usar, tirar". Empresas como Patagonia y Interface lideran este modelo.</p><div class="summary"><h2>Resumen del Capítulo 19</h2><ul><li>El cambio climático es la mayor externalidad negativa de la historia</li><li>Actuar hoy cuesta 1-2% del PIB; la inacción puede costar el 20%</li><li>Instrumentos: impuesto al carbono, cap and trade, subsidios verdes</li><li>Las renovables ya generan el 35% de la electricidad mundial</li><li>La economía circular reemplaza el modelo "fabricar, usar, tirar"</li></ul></div>`,
    quiz:{lang:"es",questions:[
      {q:"Según el Informe Stern, ¿cuánto costaría no actuar ante el cambio climático?",options:["1-2% del PIB","5% del PIB","20% del PIB","50% del PIB"],answer:2},
      {q:"¿Cuánto ha caído el costo de la energía solar en la última década?",options:["30%","60%","90%","10%"],answer:2},
      {q:"¿Qué porcentaje de la electricidad mundial generaron las renovables en 2025?",options:["10%","20%","35%","50%"],answer:2},
      {q:"¿Qué es el sistema 'Cap and Trade'?",options:["Un impuesto fijo al carbono","Límite de emisiones + mercado para comprar/vender derechos de emisión","Subsidio a empresas contaminantes","Regulación de precios de energía"],answer:1},
      {q:"¿Cuánta inversión limpia anual se necesita para 2030 según la AIE?",options:["$500 mil millones","$1 billón","$4 billones","$10 billones"],answer:2},
      {q:"¿Qué es la economía circular?",options:["Una economía que siempre crece","Modelo donde se reutilizan y reciclan productos en lugar de tirarlos","Economía basada solo en el sector servicios","Comercio entre países circulares"],answer:1},
      {q:"¿Cuánto costaría actuar hoy ante el cambio climático según el Informe Stern?",options:["1-2% del PIB anual","5-10% del PIB","20% del PIB","0% (sin costo)"],answer:0},
      {q:"¿Cuál es el principal problema económico del cambio climático?",options:["Falta de petróleo","Es la mayor externalidad negativa de la historia humana","Exceso de producción industrial","Alta inflación"],answer:1},
      {q:"¿Qué empresa es ejemplo de economía circular en el texto?",options:["Amazon","Apple","Patagonia","Tesla"],answer:2},
      {q:"Un impuesto al carbono pone un precio directo a:",options:["El consumo de electricidad","Las emisiones de CO₂","Los vehículos en general","Las importaciones de petróleo"],answer:1},
    ]}
  },
  { n:20, title:"El Futuro de la Economía Global", sub:"Megatendencias que moldearán la economía del siglo XXI: demografía, IA, multipolaridad, deuda y la transición a una nueva era económica.",
    body:`<h2>Megatendencia 1: El Envejecimiento Poblacional</h2><p>Para 2050, habrá más personas mayores de 65 años que menores de 15 en muchos países desarrollados. Esto presionará los sistemas de pensiones, salud y mercados laborales. El ratio de trabajadores por jubilado caerá de 5:1 hoy a 2:1 en 2050.</p><div class="highlight-box"><strong>Economías más afectadas:</strong> Japón (ya en contracción poblacional), Corea del Sur (tasa de natalidad 0.72 — la más baja del mundo), Alemania, Italia y China (por décadas de política del hijo único).</div><h2>Megatendencia 2: La IA y la Automatización</h2><p>La IA generativa, los robots y el machine learning automatizarán entre el 25-50% de las tareas laborales actuales según McKinsey (2030). Crearán nuevos empleos, pero habrá una disrupción masiva en la transición.</p><h2>Megatendencia 3: El Mundo Multipolar</h2><p>El dominio económico de EE.UU. y Europa está siendo desafiado. En 2023, el PIB combinado de los países BRICS+ (Brasil, Rusia, India, China, Sudáfrica + nuevos miembros) superó al del G7 en paridad de poder adquisitivo.</p><div class="example"><strong>China vs. EE.UU.:</strong> China podría convertirse en la mayor economía del mundo (nominal) entre 2030-2040. Sin embargo, enfrenta déficit demográfico, deuda inmobiliaria y tensiones geopolíticas.</div><h2>Megatendencia 4: La Deuda Global y los Límites del Crecimiento</h2><p>La deuda global (pública + privada) alcanzó el 350% del PIB mundial en 2024. Altas tasas de interés para combatir la inflación post-COVID hacen que el servicio de esta deuda sea una carga creciente.</p><h2>Megatendencia 5: La Nueva Geografía del Comercio</h2><p>La guerra comercial EE.UU.-China y las tensiones geopolíticas están creando dos bloques tecnológicos y comerciales separados (<strong>decoupling</strong>). Los países del "Sur Global" — India, Vietnam, México — se benefician del reshoring y la diversificación de cadenas de suministro.</p><div class="summary"><h2>Resumen del Capítulo 20</h2><ul><li>Envejecimiento: ratio trabajadores/jubilados caerá de 5:1 a 2:1 para 2050</li><li>La IA automatizará el 25-50% de las tareas laborales (McKinsey 2030)</li><li>Los BRICS+ ya superan al G7 en paridad de poder adquisitivo</li><li>La deuda global alcanza el 350% del PIB mundial</li><li>El decoupling EE.UU.-China crea dos bloques económicos separados</li></ul></div>`,
    quiz:{lang:"es",questions:[
      {q:"¿A cuánto caerá el ratio trabajadores por jubilado para 2050?",options:["4:1","3:1","2:1","1:1"],answer:2},
      {q:"¿Qué país tiene la tasa de natalidad más baja del mundo según el texto?",options:["Japón","Alemania","China","Corea del Sur"],answer:3},
      {q:"Según McKinsey, ¿qué porcentaje de tareas laborales automatizará la IA para 2030?",options:["5-10%","25-50%","70-90%","100%"],answer:1},
      {q:"¿Cuándo podría China convertirse en la mayor economía del mundo (nominal)?",options:["Ya lo es en 2026","2027-2028","2030-2040","2050-2060"],answer:2},
      {q:"¿Qué alcanzó la deuda global en 2024?",options:["100% del PIB mundial","200% del PIB mundial","350% del PIB mundial","500% del PIB mundial"],answer:2},
      {q:"¿Qué es el 'decoupling' económico?",options:["Mayor integración comercial","Separación en dos bloques tecnológicos y comerciales (EE.UU. vs China)","Reducción de la deuda global","Aumento del libre comercio"],answer:1},
      {q:"Los BRICS+ en paridad de poder adquisitivo ya superan a:",options:["Solo a Europa","Al G20","Al G7","Solo a EE.UU."],answer:2},
      {q:"¿Qué países se benefician del reshoring según el texto?",options:["Japón y Corea del Sur","EE.UU. y Europa","India, Vietnam y México","Rusia y Brasil"],answer:2},
      {q:"¿Por qué China enfrenta desafíos económicos futuros?",options:["Por exceso de innovación","Por déficit demográfico, deuda inmobiliaria y tensiones geopolíticas","Por excesiva integración comercial","Por falta de reservas de dólares"],answer:1},
      {q:"Las altas tasas de interés post-COVID afectan principalmente a:",options:["Las exportaciones","El servicio de la deuda global acumulada","La tasa de natalidad","El comercio digital"],answer:1},
    ]}
  },
];

const dir = "public/content/";
for (const c of caps) {
  const fname = `ECONOMIA CAP ${c.n} ${c.title.replace(/[:/]/g," ")} ESF.html`;
  const html = makeHTML(tealStyle, `Economía · Capítulo ${c.n}`, c.title, c.sub, c.body, c.quiz);
  fs.writeFileSync(dir + fname, html, "utf8");
  console.log("✓", fname);
}
console.log("Done economia");
