const fs = require("fs");

const blueStyle = `*{box-sizing:border-box;margin:0;padding:0}body{font-family:Georgia,'Times New Roman',serif;background:#f8f9fa;color:#1a1a2e;line-height:1.8}.wrapper{max-width:860px;margin:0 auto;background:#fff;padding:60px 72px;min-height:100vh}.course-tag{font-family:Arial,sans-serif;font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:.15em;color:#1d4ed8;margin-bottom:12px}h1{font-size:2rem;font-weight:700;color:#0f172a;margin-bottom:8px;line-height:1.3}.subtitle{font-size:1.05rem;color:#64748b;margin-bottom:40px;font-style:italic}hr{border:none;border-top:2px solid #bfdbfe;margin:32px 0}h2{font-size:1.35rem;font-weight:700;color:#1e293b;margin:36px 0 16px}h3{font-size:1.1rem;font-weight:700;color:#1d4ed8;margin:24px 0 10px}p{margin-bottom:16px;font-size:1rem}ul,ol{margin:16px 0 16px 24px}li{margin-bottom:8px;font-size:1rem}.highlight-box{background:#eff6ff;border-left:4px solid #3b82f6;padding:20px 24px;border-radius:0 8px 8px 0;margin:24px 0}.example{background:#f1f5f9;border:1px solid #e2e8f0;border-radius:8px;padding:20px 24px;margin:20px 0}table{width:100%;border-collapse:collapse;margin:24px 0;font-size:.95rem}th{background:#1d4ed8;color:#fff;padding:12px 16px;text-align:left;font-family:Arial,sans-serif;font-weight:600}td{padding:11px 16px;border-bottom:1px solid #e2e8f0}tr:nth-child(even) td{background:#eff6ff}.summary{background:#0f172a;color:#e2e8f0;border-radius:12px;padding:28px 32px;margin:40px 0 0}.summary h2{color:#60a5fa;margin-top:0}.summary li{color:#cbd5e1}@media(max-width:640px){.wrapper{padding:32px 24px}h1{font-size:1.5rem}}`;

function makeHTML(tag, title, subtitle, body, quizData) {
  return `<!DOCTYPE html>\n<html lang="es">\n<head>\n  <meta charset="UTF-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n  <title>${title} | Español Sin Fronteras</title>\n  <style>${blueStyle}</style>\n</head>\n<body>\n<div class="wrapper">\n  <div class="course-tag">${tag}</div>\n  <h1>${title}</h1>\n  <p class="subtitle">${subtitle}</p>\n  <hr>\n${body}\n</div>\n<script>\nwindow.QUIZ_DATA = ${JSON.stringify(quizData, null, 2)};\n</script>\n<script src="quiz-engine.js"></script>\n</body>\n</html>`;
}

const caps = [
  { n:11, file:"MARKETS CAP 11 El Mercado de Divisas Forex ESF.html", title:"El Mercado de Divisas (Forex)", sub:"El mercado más grande del mundo: cómo funciona el intercambio de monedas, los pares de divisas y las estrategias de trading de FX.",
    body:`<h2>¿Qué es el Mercado Forex?</h2><p>El <strong>Forex</strong> (Foreign Exchange) es el mercado donde se intercambian las monedas del mundo. Con un volumen diario de <strong>más de $7.5 billones</strong>, es el mercado financiero más grande y líquido del planeta — opera las 24 horas, 5 días a la semana.</p><div class="highlight-box"><strong>Sin sede física:</strong> El Forex no tiene una bolsa central. Es un mercado OTC (over-the-counter) descentralizado donde los participantes negocian directamente entre sí a través de redes electrónicas.</div><h2>Los Pares de Divisas</h2><table><tr><th>Par</th><th>Nombre</th><th>Participación en el mercado</th></tr><tr><td>EUR/USD</td><td>Euro / Dólar</td><td>~23% del volumen total</td></tr><tr><td>USD/JPY</td><td>Dólar / Yen</td><td>~14%</td></tr><tr><td>GBP/USD</td><td>Libra / Dólar ("Cable")</td><td>~10%</td></tr><tr><td>USD/CHF</td><td>Dólar / Franco suizo</td><td>~5%</td></tr><tr><td>AUD/USD</td><td>Dólar australiano / Dólar</td><td>~5%</td></tr></table><h2>Factores que Mueven las Divisas</h2><ul><li><strong>Tasas de interés</strong>: Monedas de países con tasas altas atraen capital (apreciación)</li><li><strong>Inflación</strong>: Alta inflación debilita la moneda</li><li><strong>PIB y crecimiento</strong>: Economías fuertes tienen monedas más fuertes</li><li><strong>Política y estabilidad</strong>: Incertidumbre política deprecia la moneda</li><li><strong>Flujos comerciales</strong>: Superávit comercial eleva la demanda de la moneda</li></ul><div class="example"><strong>Carry trade:</strong> Estrategia de pedir prestado en monedas de baja tasa (JPY) e invertir en monedas de alta tasa (MXN). Funciona bien en mercados estables; muy peligroso en crisis.</div><div class="summary"><h2>Resumen del Capítulo 11</h2><ul><li>El Forex mueve $7.5 billones diarios — el mercado más grande del mundo</li><li>Opera 24h/5d de forma descentralizada (OTC)</li><li>EUR/USD es el par más negociado (~23% del volumen)</li><li>Las tasas de interés son el principal factor que mueve las divisas</li><li>El carry trade aprovecha diferenciales de tasas entre países</li></ul></div>`,
    quiz:{lang:"es",questions:[
      {q:"¿Cuál es el volumen diario aproximado del mercado Forex?",options:["$500 mil millones","$2 billones","$7.5 billones","$20 billones"],answer:2},
      {q:"¿Qué significa OTC en el mercado Forex?",options:["Open Trading Centre","Over-the-counter (mercado descentralizado sin sede física)","Official Trading Currency","Online Transaction Control"],answer:1},
      {q:"¿Cuál es el par de divisas más negociado del mundo?",options:["USD/JPY","GBP/USD","EUR/USD","USD/CHF"],answer:2},
      {q:"¿Cuántas horas al día opera el mercado Forex?",options:["8 horas","12 horas","16 horas","24 horas"],answer:3},
      {q:"¿Qué efecto tiene una tasa de interés alta en una moneda?",options:["La deprecia","La mantiene estable","La aprecia al atraer capital","No tiene efecto"],answer:2},
      {q:"El 'cable' es el apodo del par:",options:["EUR/USD","USD/JPY","GBP/USD","AUD/USD"],answer:2},
      {q:"¿En qué consiste el carry trade?",options:["Cambiar divisas en el aeropuerto","Pedir prestado en monedas de baja tasa e invertir en monedas de alta tasa","Comprar y vender el mismo par en segundos","Invertir solo en dólares"],answer:1},
      {q:"Una alta inflación generalmente tiene qué efecto sobre la moneda de un país?",options:["La fortalece","La debilita","No tiene efecto","La hace más estable"],answer:1},
      {q:"¿Cuántos días a la semana opera el mercado Forex?",options:["3 días","5 días","6 días","7 días"],answer:1},
      {q:"¿Qué par involucra al yen japonés?",options:["EUR/USD","USD/JPY","GBP/USD","AUD/USD"],answer:1},
    ]}
  },
  { n:12, file:"MARKETS CAP 12 Materias Primas Oro Petroleo ESF.html", title:"Materias Primas: Oro, Petróleo y Más", sub:"Los mercados de commodities: cómo se negocian el oro, el petróleo, los metales y los alimentos, y su impacto en la economía global.",
    body:`<h2>¿Qué Son las Materias Primas?</h2><p>Las <strong>materias primas</strong> (commodities) son bienes físicos estandarizados que se producen y consumen en grandes cantidades. Se dividen en cuatro categorías principales y se negocian en bolsas especializadas o mercados de futuros.</p><table><tr><th>Categoría</th><th>Ejemplos</th><th>Bolsa Principal</th></tr><tr><td>Energía</td><td>Petróleo crudo, gas natural, gasolina</td><td>NYMEX, ICE</td></tr><tr><td>Metales preciosos</td><td>Oro, plata, platino</td><td>COMEX</td></tr><tr><td>Metales industriales</td><td>Cobre, aluminio, níquel</td><td>LME (Londres)</td></tr><tr><td>Agrícolas</td><td>Trigo, maíz, soja, café, azúcar</td><td>CBOT (Chicago)</td></tr></table><h2>El Oro Como Activo</h2><p>El oro tiene un rol único: es simultáneamente materia prima, reserva de valor y activo refugio. Sube en momentos de crisis, inflación e incertidumbre. En junio 2026, el precio del oro supera los <strong>$3,300/oz</strong>.</p><div class="highlight-box"><strong>Regla general:</strong> El oro sube cuando el dólar baja y cuando los inversores temen la inflación o las crisis geopolíticas. Tiene correlación negativa con las tasas de interés reales.</div><h2>El Petróleo y la OPEP</h2><p>El <strong>petróleo crudo</strong> (Brent y WTI) es la materia prima más negociada del mundo. La <strong>OPEP+</strong> (Arabia Saudí, Rusia y aliados) controla ~40% de la producción mundial y puede influir significativamente en los precios mediante recortes o aumentos de producción.</p><div class="example"><strong>Precio 2026:</strong> El petróleo Brent cotiza alrededor de $75-85/barril, con presión bajista por el avance de los vehículos eléctricos y al alza por tensiones en Oriente Medio.</div><h2>Cobre: El "Doctor Copper"</h2><p>El cobre es llamado "Doctor Copper" porque su precio predice el estado de la economía global. Cuando el cobre sube, la economía está creciendo (más construcción, más electrónica). Es clave para la transición energética (vehículos eléctricos, eólica, solar).</p><div class="summary"><h2>Resumen del Capítulo 12</h2><ul><li>Commodities: energía, metales preciosos, metales industriales y agrícolas</li><li>El oro supera $3,300/oz en 2026 como activo refugio</li><li>La OPEP+ controla ~40% de la producción mundial de petróleo</li><li>El Brent cotiza ~$75-85/barril en 2026</li><li>El cobre predice el ciclo económico global</li></ul></div>`,
    quiz:{lang:"es",questions:[
      {q:"¿Dónde se negocian principalmente los metales preciosos como el oro?",options:["NYSE","NYMEX","COMEX","CBOT"],answer:2},
      {q:"¿Cuál es el precio aproximado del oro en junio 2026?",options:["$1,500/oz","$2,000/oz","$3,300/oz","$5,000/oz"],answer:2},
      {q:"¿Qué porcentaje de la producción mundial de petróleo controla la OPEP+?",options:["10%","25%","~40%","60%"],answer:2},
      {q:"¿Cuáles son los dos benchmarks principales del petróleo crudo?",options:["WTI y Dubai","Brent y WTI","NYMEX y ICE","Arabia y Texas"],answer:1},
      {q:"¿Por qué el cobre es llamado 'Doctor Copper'?",options:["Se usa en medicina","Su precio predice el estado de la economía global","Es el metal más escaso","Es el más caro de los metales industriales"],answer:1},
      {q:"¿Cuándo tiende a subir el precio del oro?",options:["Cuando el dólar sube y hay estabilidad","En crisis, inflación e incertidumbre geopolítica","Cuando suben las tasas de interés reales","Solo en verano"],answer:1},
      {q:"¿En qué bolsa se negocian principalmente los cereales como el trigo y el maíz?",options:["LME","COMEX","CBOT","ICE"],answer:2},
      {q:"¿Cuál es el rango de precio del Brent en 2026?",options:["$30-40/barril","$50-60/barril","$75-85/barril","$100-120/barril"],answer:2},
      {q:"¿Qué materia prima es clave para la transición a vehículos eléctricos?",options:["Petróleo","Oro","Cobre","Gas natural"],answer:2},
      {q:"¿Qué efecto tiene el avance de los vehículos eléctricos sobre el petróleo?",options:["Presión al alza en el precio","Presión bajista en el precio","Ningún efecto","Estabiliza el precio"],answer:1},
    ]}
  },
  { n:13, file:"MARKETS CAP 13 Mercados Emergentes ESF.html", title:"Mercados Emergentes", sub:"Las economías en desarrollo como oportunidad de inversión: altos retornos potenciales, mayores riesgos y las claves para invertir en ellos.",
    body:`<h2>¿Qué Son los Mercados Emergentes?</h2><p>Los <strong>mercados emergentes</strong> son economías en transición entre países en vías de desarrollo y países desarrollados. Crecen más rápido que los desarrollados pero conllevan mayores riesgos políticos, de divisas e institucionales.</p><div class="highlight-box"><strong>Los grandes emergentes:</strong> Los países BRICS originales — Brasil, Rusia, India, China y Sudáfrica — representan colectivamente más del 40% del PIB mundial en paridad de poder adquisitivo.</div><h2>Características de los Mercados Emergentes</h2><table><tr><th>Aspecto</th><th>Mercados Desarrollados</th><th>Mercados Emergentes</th></tr><tr><td>Crecimiento PIB</td><td>1-3% anual</td><td>4-7% anual (típico)</td></tr><tr><td>Riesgo político</td><td>Bajo</td><td>Medio a alto</td></tr><tr><td>Liquidez bursátil</td><td>Alta</td><td>Media a baja</td></tr><tr><td>Riesgo de divisa</td><td>Bajo</td><td>Alto</td></tr><tr><td>Rendimientos potenciales</td><td>Moderados</td><td>Altos</td></tr></table><h2>Riesgos Específicos</h2><ul><li><strong>Riesgo político</strong>: Cambios de gobierno, expropiaciones, corrupción</li><li><strong>Riesgo de divisa</strong>: Las monedas emergentes pueden depreciarse rápidamente</li><li><strong>Riesgo de liquidez</strong>: Mercados menos profundos, difícil vender en crisis</li><li><strong>Riesgo regulatorio</strong>: Cambios de reglas del juego (China 2021: regulación tecnológica)</li></ul><div class="example"><strong>India en 2026:</strong> Con una población de 1,450 millones y el mayor crecimiento del PIB entre las grandes economías (~7%), India es el mercado emergente más atractivo para inversores globales en 2026.</div><h2>Cómo Invertir en Emergentes</h2><ul><li>ETFs de mercados emergentes (iShares EEM, Vanguard VWO)</li><li>Acciones individuales en bolsas locales o ADRs</li><li>Bonos soberanos en dólares (mayor seguridad) o en moneda local (mayor riesgo/retorno)</li><li>Fondos mutuos especializados</li></ul><div class="summary"><h2>Resumen del Capítulo 13</h2><ul><li>Los mercados emergentes crecen 4-7% anual vs 1-3% en desarrollados</li><li>BRICS+ = más del 40% del PIB mundial en PPA</li><li>Riesgos específicos: político, divisa, liquidez, regulatorio</li><li>India es el emergente más atractivo en 2026 (~7% crecimiento)</li><li>ETFs como EEM o VWO son la forma más sencilla de acceder</li></ul></div>`,
    quiz:{lang:"es",questions:[
      {q:"¿Cuál es el crecimiento del PIB típico de los mercados emergentes?",options:["1-2% anual","4-7% anual","10-15% anual","0% anual"],answer:1},
      {q:"¿Qué países forman los BRICS originales?",options:["Bolivia, Rusia, India, China, Sudáfrica","Brasil, Rusia, India, China, Sudáfrica","Brasil, Rumania, Indonesia, China, Suiza","Brasil, Rusia, Irán, Cuba, Sudán"],answer:1},
      {q:"¿Qué porcentaje del PIB mundial representan los BRICS en PPA?",options:["10%","25%","Más del 40%","60%"],answer:2},
      {q:"¿Cuál es el principal riesgo de invertir en mercados emergentes?",options:["Bajo crecimiento","Exceso de regulación","Riesgos político, de divisa y liquidez","Tasas de interés muy bajas"],answer:2},
      {q:"¿Qué mercado emergente es el más atractivo en 2026 según el texto?",options:["China","Brasil","India","México"],answer:2},
      {q:"¿Qué tasa de crecimiento tiene India en 2026?",options:["~3%","~5%","~7%","~10%"],answer:2},
      {q:"¿Qué ETF popular da acceso a mercados emergentes?",options:["SPY","QQQ","EEM","DIA"],answer:2},
      {q:"¿Qué es un ADR?",options:["Un tipo de bono soberano","Acción de empresa extranjera listada en bolsas de EE.UU.","Un fondo de cobertura","Un índice de emergentes"],answer:1},
      {q:"El riesgo regulatorio en China se evidenció en 2021 con:",options:["La nacionalización de empresas","La regulación agresiva del sector tecnológico","La prohibición del dólar","El cierre de la bolsa de Shanghai"],answer:1},
      {q:"Los bonos soberanos en dólares de emergentes implican qué riesgo vs los de moneda local?",options:["Mayor riesgo de divisa","Menor riesgo de divisa pero menor retorno potencial","Mismo riesgo","Mayor riesgo de default"],answer:1},
    ]}
  },
  { n:14, file:"MARKETS CAP 14 La Reserva Federal y los Mercados ESF.html", title:"La Reserva Federal y los Mercados", sub:"Cómo las decisiones del banco central más poderoso del mundo mueven los mercados financieros globales.",
    body:`<h2>¿Qué es la Reserva Federal?</h2><p>La <strong>Reserva Federal</strong> (Fed) es el banco central de los Estados Unidos, creado en 1913. Tiene dos mandatos: <strong>máximo empleo</strong> y <strong>estabilidad de precios</strong> (inflación objetivo del 2%). Sus decisiones de política monetaria afectan a los mercados globales.</p><div class="highlight-box"><strong>El poder de la Fed:</strong> Cuando la Fed habla, los mercados globales escuchan. Cambios en las expectativas sobre las tasas de interés de EE.UU. pueden mover bolsas, bonos y divisas en todo el mundo en segundos.</div><h2>Herramientas de la Reserva Federal</h2><table><tr><th>Herramienta</th><th>Descripción</th><th>Efecto en Mercados</th></tr><tr><td>Fed Funds Rate</td><td>Tasa de interés objetivo para préstamos interbancarios</td><td>Afecta todas las tasas del sistema</td></tr><tr><td>QE (Quantitative Easing)</td><td>Compra de bonos para inyectar liquidez</td><td>Sube bolsas, baja rendimientos bonos</td></tr><tr><td>QT (Quantitative Tightening)</td><td>Vende bonos para retirar liquidez</td><td>Presiona bolsas a la baja</td></tr><tr><td>Forward Guidance</td><td>Comunicación de intenciones futuras</td><td>Mueve expectativas del mercado</td></tr></table><h2>El Ciclo de Tasas y los Mercados</h2><p>Históricamente: <strong>Tasas bajas</strong> → dinero barato → bolsas suben, bonos suben. <strong>Tasas altas</strong> → dinero caro → bolsas presionadas, bonos caen (precio), dólar sube.</p><div class="example"><strong>2022-2024:</strong> La Fed subió tasas de 0% a 5.5% para combatir la inflación post-COVID. El S&P 500 cayó ~20% en 2022. En 2024 comenzó a bajar tasas — los mercados rebotaron con fuerza.</div><h2>El "Fed Put" y la Dependencia del Mercado</h2><p>Los mercados asumen que si caen mucho, la Fed intervendrá (bajará tasas o hará QE). Esta creencia — el "Fed Put" — hace que los inversores tomen más riesgo. Algunos economistas creen que esto crea burbujas.</p><div class="summary"><h2>Resumen del Capítulo 14</h2><ul><li>La Fed tiene 2 mandatos: máximo empleo + inflación del 2%</li><li>Herramientas: Fed Funds Rate, QE, QT, Forward Guidance</li><li>Tasas bajas = bolsas arriba; tasas altas = bolsas presionadas</li><li>La Fed subió tasas de 0% a 5.5% en 2022-2024 para combatir la inflación</li><li>El "Fed Put" es la expectativa de que la Fed rescatará los mercados</li></ul></div>`,
    quiz:{lang:"es",questions:[
      {q:"¿En qué año fue creada la Reserva Federal?",options:["1776","1865","1913","1945"],answer:2},
      {q:"¿Cuáles son los dos mandatos de la Fed?",options:["Control de la deuda y estabilidad cambiaria","Máximo empleo y estabilidad de precios (inflación 2%)","Crecimiento del PIB y superávit fiscal","Fortaleza del dólar y reducción de la deuda"],answer:1},
      {q:"¿Qué es el QE (Quantitative Easing)?",options:["Subir las tasas de interés","Compra de bonos por la Fed para inyectar liquidez","Venta de bonos para retirar liquidez","Reducir el déficit fiscal"],answer:1},
      {q:"¿Qué ocurre típicamente en bolsas cuando la Fed sube las tasas?",options:["Las bolsas suben fuertemente","Las bolsas se mantienen estables","Las bolsas son presionadas a la baja","El dólar cae"],answer:2},
      {q:"¿A qué nivel subió la Fed Funds Rate entre 2022-2024?",options:["2%","3.5%","5.5%","7%"],answer:2},
      {q:"¿Qué es el 'Fed Put'?",options:["Un tipo de opción financiera de la Fed","La expectativa de que la Fed intervendrá si los mercados caen mucho","La política de bajar tasas cada año","Un programa de compra de acciones"],answer:1},
      {q:"¿Qué efecto tiene el QT (Quantitative Tightening)?",options:["Inyecta liquidez al sistema","Baja las tasas de interés","Retira liquidez del sistema presionando bolsas a la baja","Sube el precio de los bonos"],answer:2},
      {q:"El Forward Guidance de la Fed sirve para:",options:["Fijar el precio del dólar","Comunicar intenciones futuras y mover expectativas del mercado","Regular los bancos comerciales","Establecer el salario mínimo"],answer:1},
      {q:"¿Qué pasó con el S&P 500 en 2022 cuando la Fed subió tasas agresivamente?",options:["Subió un 20%","Cayó aproximadamente un 20%","Se mantuvo estable","Subió un 40%"],answer:1},
      {q:"¿Qué afirman algunos economistas sobre el 'Fed Put'?",options:["Es siempre beneficioso para la economía","Puede crear burbujas al incentivar toma de riesgo excesiva","No existe en la práctica","Solo aplica a bonos"],answer:1},
    ]}
  },
  { n:15, file:"MARKETS CAP 15 Psicologia del Inversor ESF.html", title:"Psicología del Inversor", sub:"Las emociones, sesgos y errores cognitivos que destruyen retornos — y cómo construir una mentalidad ganadora a largo plazo.",
    body:`<h2>Por Qué la Psicología Importa en los Mercados</h2><p>Los mercados no son racionales — están formados por millones de seres humanos tomando decisiones emocionales. Entender la psicología del inversor es tan importante como entender el análisis técnico o fundamental.</p><div class="highlight-box"><strong>Dato impactante:</strong> El S&P 500 rindió un 9.9% anual en los últimos 30 años. El inversor promedio solo obtuvo un 4.7% anual en el mismo período (Dalbar Study). La diferencia: el comportamiento emocional.</div><h2>El Ciclo Emocional del Mercado</h2><p>Los mercados siguen un ciclo emocional predecible:</p><ol><li><strong>Optimismo</strong> → <strong>Emoción</strong> → <strong>Euforia</strong> (máximo del mercado)</li><li><strong>Ansiedad</strong> → <strong>Negación</strong> → <strong>Miedo</strong> → <strong>Pánico</strong></li><li><strong>Capitulación</strong> (mínimo del mercado) → <strong>Depresión</strong></li><li><strong>Esperanza</strong> → <strong>Alivio</strong> → <strong>Optimismo</strong> (el ciclo se reinicia)</li></ol><div class="example"><strong>La lección:</strong> El momento de máxima euforia es el peor momento para comprar. El momento de máximo pánico es históricamente el mejor momento para comprar.</div><h2>Sesgos del Inversor</h2><table><tr><th>Sesgo</th><th>Descripción</th><th>Cómo Evitarlo</th></tr><tr><td>Aversión a las pérdidas</td><td>Las pérdidas duelen 2x más que las ganancias</td><td>Tener reglas de stop-loss definidas</td></tr><tr><td>Efecto disposición</td><td>Vender ganadoras demasiado pronto, mantener perdedoras</td><td>Analizar por fundamentos, no por precio de compra</td></tr><tr><td>Sesgo de confirmación</td><td>Buscar solo información que confirme tu tesis</td><td>Buscar activamente tesis contrarias</td></tr><tr><td>Mentalidad de rebaño</td><td>Seguir a la multitud</td><td>Estrategia de inversión escrita previa</td></tr></table><h2>Hábitos del Inversor Exitoso</h2><ul><li>Invertir sistemáticamente (Dollar Cost Averaging)</li><li>No ver la cartera más de una vez al mes</li><li>Tener una política de inversión escrita (IPS)</li><li>Separar las emociones de las decisiones financieras</li><li>Pensar en décadas, no en días</li></ul><div class="summary"><h2>Resumen del Capítulo 15</h2><ul><li>El inversor promedio gana 4.7% vs 9.9% del S&P 500 por decisiones emocionales</li><li>Los mercados siguen un ciclo emocional: euforia (máximo) → pánico (mínimo)</li><li>Sesgos clave: aversión a pérdidas, efecto disposición, confirmación, rebaño</li><li>El DCA (compra sistemática) elimina el timing emocional</li><li>La mejor estrategia: tener un plan escrito y cumplirlo sin importar el mercado</li></ul></div>`,
    quiz:{lang:"es",questions:[
      {q:"¿Qué rendimiento anual obtuvo el S&P 500 en los últimos 30 años?",options:["4.7%","7%","9.9%","15%"],answer:2},
      {q:"¿Qué rendimiento obtuvo el inversor promedio en ese mismo período?",options:["4.7%","7%","9.9%","12%"],answer:0},
      {q:"¿En qué fase del ciclo emocional se produce el máximo del mercado?",options:["Optimismo","Esperanza","Pánico","Euforia"],answer:3},
      {q:"¿Cuándo es históricamente el mejor momento para comprar?",options:["Durante la euforia","Cuando todos compran","Durante el máximo pánico / capitulación","Cuando el mercado lleva subiendo 2 años"],answer:2},
      {q:"El 'efecto disposición' hace que los inversores:",options:["Compren en los mínimos","Mantengan perdedoras demasiado tiempo y vendan ganadoras muy pronto","Diversifiquen demasiado","Inviertan solo en bonos"],answer:1},
      {q:"La aversión a las pérdidas significa que las pérdidas duelen:",options:["Igual que las ganancias","El doble que las ganancias equivalentes","La mitad","10 veces más"],answer:1},
      {q:"¿Qué es el Dollar Cost Averaging (DCA)?",options:["Invertir toda la cantidad en un solo momento","Comprar más cuando el mercado sube","Invertir cantidades fijas regularmente sin importar el precio","Comprar solo acciones en dólares"],answer:2},
      {q:"¿Cuál es un hábito recomendado para el inversor exitoso?",options:["Ver la cartera varias veces al día","No tener un plan escrito","Invertir sistemáticamente y pensar en décadas","Seguir siempre las noticias financieras"],answer:2},
      {q:"El sesgo de confirmación en inversión lleva a:",options:["Buscar solo información que confirma tu tesis","Diversificar demasiado","Vender demasiado pronto","Invertir en mercados emergentes"],answer:0},
      {q:"¿Qué es una IPS (Investment Policy Statement)?",options:["Un fondo de inversión especial","Una política de inversión escrita que guía las decisiones","Un tipo de bono del gobierno","Un índice de rentabilidad"],answer:1},
    ]}
  },
  { n:16, file:"MARKETS CAP 16 Trading Algoritmico y Alta Frecuencia ESF.html", title:"Trading Algorítmico y Alta Frecuencia", sub:"Cómo los algoritmos y los ordenadores han tomado el control de los mercados financieros modernos.",
    body:`<h2>¿Qué es el Trading Algorítmico?</h2><p>El <strong>trading algorítmico</strong> usa programas informáticos para ejecutar órdenes de compra/venta según reglas predefinidas — velocidad, precio, volumen — sin intervención humana directa. Hoy representa más del <strong>70-80% del volumen</strong> de negociación en bolsas de EE.UU.</p><div class="highlight-box"><strong>HFT (High Frequency Trading):</strong> La forma más extrema del trading algorítmico. Los HFT ejecutan millones de operaciones en microsegundos, aprovechando diferencias de precio mínimas. Empresas como Citadel Securities, Virtu Financial y Jump Trading dominan este espacio.</div><h2>Tipos de Estrategias Algorítmicas</h2><table><tr><th>Estrategia</th><th>Descripción</th></tr><tr><td>Market Making</td><td>Ofrece siempre precio de compra y venta para ganar el spread</td></tr><tr><td>Arbitraje estadístico</td><td>Explota desviaciones temporales entre activos correlacionados</td></tr><tr><td>Momentum</td><td>Sigue tendencias detectadas por señales técnicas</td></tr><tr><td>Mean Reversion</td><td>Apuesta a que los precios vuelvan a su media histórica</td></tr><tr><td>Arbitraje de latencia</td><td>Gana ventaja por estar más cerca de los servidores de la bolsa</td></tr></table><h2>¿Son Buenos los Algoritmos para los Mercados?</h2><p><strong>Ventajas:</strong> Mayor liquidez, spreads más ajustados (mejores precios para inversores), mercados más eficientes.</p><p><strong>Riesgos:</strong> Flash crashes (caídas repentinas en minutos), cascadas de ventas automáticas, riesgo sistémico si muchos algoritmos hacen lo mismo simultáneamente.</p><div class="example"><strong>Flash Crash del 6 de mayo de 2010:</strong> El Dow Jones cayó 1,000 puntos (9%) en minutos y luego se recuperó casi completamente. Fue causado por una interacción imprevista entre algoritmos.</div><h2>Inversión Cuantitativa (Quant)</h2><p>Los fondos cuantitativos (como Renaissance Technologies) usan matemáticas avanzadas, estadística y machine learning para encontrar patrones en los datos del mercado. El Medallion Fund de Renaissance ha generado retornos del ~66% anual bruto desde 1988.</p><div class="summary"><h2>Resumen del Capítulo 16</h2><ul><li>El trading algorítmico representa el 70-80% del volumen en bolsas de EE.UU.</li><li>HFT: millones de operaciones en microsegundos</li><li>Estrategias: market making, arbitraje, momentum, mean reversion</li><li>Riesgo sistémico: flash crashes por interacciones imprevistas de algoritmos</li><li>Renaissance Technologies: ~66% anual bruto con estrategias cuantitativas</li></ul></div>`,
    quiz:{lang:"es",questions:[
      {q:"¿Qué porcentaje del volumen en bolsas de EE.UU. representa el trading algorítmico?",options:["20-30%","40-50%","70-80%","95%"],answer:2},
      {q:"¿Qué significa HFT?",options:["High Fundamental Trading","High Frequency Trading","Hedge Fund Trading","Historical Finance Trends"],answer:1},
      {q:"¿Cuál es la ventaja principal del trading algorítmico para el inversor minorista?",options:["Permite ganar siempre","Mayor liquidez y spreads más ajustados","Elimina el riesgo de pérdidas","Acceso a información privilegiada"],answer:1},
      {q:"¿Qué ocurrió en el Flash Crash del 6 de mayo de 2010?",options:["El Dow Jones subió 1,000 puntos en minutos","El Dow Jones cayó 1,000 puntos en minutos y luego se recuperó","La Fed pausó la negociación","Lehman Brothers quebró"],answer:1},
      {q:"¿Qué empresa es conocida por el Medallion Fund con ~66% de retorno anual bruto?",options:["Citadel","Two Sigma","Renaissance Technologies","DE Shaw"],answer:2},
      {q:"El 'arbitraje de latencia' en HFT gana ventaja por:",options:["Tener más capital","Estar físicamente más cerca de los servidores de la bolsa","Tener mejores analistas","Negociar en mercados extranjeros"],answer:1},
      {q:"¿Qué es el 'mean reversion' como estrategia algorítmica?",options:["Seguir la tendencia del mercado","Apostar a que los precios vuelvan a su media histórica","Comprar en los máximos","Hacer market making"],answer:1},
      {q:"¿Qué empresa domina el HFT junto con Jump Trading y Virtu Financial?",options:["Goldman Sachs","Citadel Securities","Morgan Stanley","JP Morgan"],answer:1},
      {q:"El arbitraje estadístico explota:",options:["Diferencias de velocidad entre algoritmos","Desviaciones temporales entre activos correlacionados","Noticias antes de que sean públicas","Diferencias de tasas entre países"],answer:1},
      {q:"¿Cuál es un riesgo sistémico del trading algorítmico?",options:["Demasiada liquidez en mercados","Cascadas de ventas automáticas si muchos algoritmos hacen lo mismo","Precios demasiado bajos para los minoristas","Mayor transparencia de mercado"],answer:1},
    ]}
  },
  { n:17, file:"MARKETS CAP 17 Los Mejores Inversores de la Historia ESF.html", title:"Los Mejores Inversores de la Historia", sub:"Las estrategias, filosofías y lecciones de los inversores más exitosos del mundo: Buffett, Munger, Lynch, Soros y más.",
    body:`<h2>Warren Buffett — El Oráculo de Omaha</h2><p><strong>Warren Buffett</strong> es el inversor más exitoso de la historia. Con una rentabilidad media del <strong>~20% anual durante 60 años</strong> a través de Berkshire Hathaway, su filosofía es simple: comprar negocios excelentes a precios razonables y mantenerlos para siempre.</p><div class="highlight-box"><strong>Cita de Buffett:</strong> "El mercado de valores es un mecanismo para transferir dinero del impaciente al paciente." Su regla más famosa: "Regla 1: No pierdas dinero. Regla 2: No olvides la Regla 1."</div><h2>Charlie Munger — El Socio Olvidado</h2><p><strong>Charlie Munger</strong> (1924-2023) fue el vicepresidente de Berkshire Hathaway y arquitecto intelectual de la estrategia de Buffett. Introdujo los "modelos mentales" — usar ideas de múltiples disciplinas (psicología, física, biología) para tomar mejores decisiones.</p><h2>Peter Lynch — El Rey de los Fondos Mutuos</h2><p>Gestionó el <strong>Fidelity Magellan Fund</strong> de 1977 a 1990, obteniendo un 29% anual — el mejor historial de cualquier fondo mutuo. Su estrategia: "Invierte en lo que conoces." Analizaba personalmente miles de empresas al año.</p><h2>George Soros — El Hombre que Quebró al Banco de Inglaterra</h2><p>En 1992, <strong>George Soros</strong> apostó $10,000 millones contra la libra esterlina cuando detectó que era insostenible dentro del Sistema Monetario Europeo. Ganó $1,000 millones en un día. Su filosofía: la "reflexividad" — los mercados son influenciados por las percepciones que crean.</p><div class="example"><strong>Benjamin Graham</strong> — Mentor de Buffett, padre del "value investing". Su libro "El Inversor Inteligente" (1949) es considerado la biblia de la inversión en valor.</div><h2>Ray Dalio — El Maestro de la Macro</h2><p>Fundador de <strong>Bridgewater Associates</strong> (el mayor hedge fund del mundo). Su principio de "All Weather Portfolio" busca funcionar bien en cualquier entorno económico diversificando entre activos que responden diferente a la inflación y el crecimiento.</p><div class="summary"><h2>Resumen del Capítulo 17</h2><ul><li>Buffett: ~20% anual 60 años; compra negocios excelentes y los mantiene</li><li>Munger: modelos mentales de múltiples disciplinas</li><li>Lynch: 29% anual con Magellan; "invierte en lo que conoces"</li><li>Soros: ganó $1,000M en un día apostando contra la libra (1992)</li><li>Dalio: "All Weather Portfolio" — funcionar en cualquier entorno</li></ul></div>`,
    quiz:{lang:"es",questions:[
      {q:"¿Cuál es la rentabilidad media anual aproximada de Warren Buffett a través de Berkshire Hathaway?",options:["~10% anual","~15% anual","~20% anual","~30% anual"],answer:2},
      {q:"¿Cuál fue el rendimiento anual de Peter Lynch con el Fidelity Magellan Fund?",options:["15%","20%","29%","40%"],answer:2},
      {q:"¿Qué hizo George Soros en 1992 con la libra esterlina?",options:["La compró masivamente","Apostó $10,000M contra ella y ganó $1,000M en un día","La vendió por pánico","Aconsejó al gobierno británico"],answer:1},
      {q:"¿Qué concepto filosófico introdujo Charlie Munger?",options:["El value investing","Los modelos mentales de múltiples disciplinas","El análisis técnico","El arbitraje estadístico"],answer:1},
      {q:"¿Quién es el padre del 'value investing'?",options:["Warren Buffett","Charlie Munger","Benjamin Graham","Peter Lynch"],answer:2},
      {q:"¿Cuál es la estrategia de inversión de Peter Lynch?",options:["Sigue los algoritmos","Invierte en lo que conoces","Solo invierte en índices","Espera las crisis para comprar"],answer:1},
      {q:"¿Qué es el 'All Weather Portfolio' de Ray Dalio?",options:["Un fondo solo de acciones","Una cartera que funciona bien en cualquier entorno económico","Una estrategia de trading de alta frecuencia","Un fondo de materias primas"],answer:1},
      {q:"¿Qué empresa fundó Ray Dalio?",options:["Renaissance Technologies","Two Sigma","Bridgewater Associates","Citadel"],answer:2},
      {q:"¿Qué libro es considerado la biblia del value investing?",options:["'El Capital' de Marx","'El Inversor Inteligente' de Graham","'Padre Rico Padre Pobre'","'Flash Boys' de Lewis"],answer:1},
      {q:"La 'reflexividad' de Soros dice que los mercados:",options:["Son siempre eficientes","Son influenciados por las percepciones que ellos mismos crean","Siguen patrones matemáticos perfectos","No pueden predecirse nunca"],answer:1},
    ]}
  },
  { n:18, file:"MARKETS CAP 18 Como Armar una Cartera de Inversion ESF.html", title:"Cómo Armar una Cartera de Inversión", sub:"Guía práctica para construir un portafolio de inversión diversificado, alineado con tus metas y tolerancia al riesgo.",
    body:`<h2>Principios de la Construcción de Cartera</h2><p>Construir una cartera de inversión no es elegir las acciones más "calientes" — es diseñar un sistema que maximice retornos para un nivel de riesgo dado, de forma consistente en el tiempo.</p><div class="highlight-box"><strong>Harry Markowitz (Premio Nobel 1990):</strong> La Teoría Moderna de Portafolios demuestra que diversificar entre activos no correlacionados reduce el riesgo sin necesariamente reducir el retorno.</div><h2>Clases de Activos</h2><table><tr><th>Clase de Activo</th><th>Retorno Histórico Anual</th><th>Riesgo (Volatilidad)</th></tr><tr><td>Acciones EE.UU. (S&P 500)</td><td>~10%</td><td>Alta (~15-20% desviación)</td></tr><tr><td>Acciones internacionales</td><td>~7-8%</td><td>Alta</td></tr><tr><td>Bonos del Tesoro EE.UU.</td><td>~3-5%</td><td>Baja</td></tr><tr><td>Bienes raíces (REITs)</td><td>~8-9%</td><td>Media</td></tr><tr><td>Oro</td><td>~5-7%</td><td>Media</td></tr><tr><td>Efectivo/Money Market</td><td>~2-4%</td><td>Muy baja</td></tr></table><h2>Modelos de Asignación de Activos</h2><ul><li><strong>Cartera 60/40</strong>: 60% acciones + 40% bonos. Clásica, balanceada, para inversores moderados.</li><li><strong>Cartera Tres Fondos</strong>: Acciones EE.UU. + Acciones internacionales + Bonos. Simple y efectiva.</li><li><strong>All Weather (Dalio)</strong>: 30% acciones, 40% bonos largo plazo, 15% bonos medio plazo, 7.5% oro, 7.5% materias primas.</li><li><strong>100% acciones</strong>: Para inversores jóvenes con horizonte de 30+ años.</li></ul><div class="example"><strong>Rebalanceo anual:</strong> Si empiezas con 60/40 y las acciones suben mucho, tu cartera se convierte en 70/30. Rebalancear = vender el exceso de acciones y comprar bonos para volver a 60/40.</div><h2>La Importancia del Horizonte Temporal</h2><p>Con 10+ años de horizonte, el riesgo de pérdida en una cartera 100% acciones cae drásticamente. El S&P 500 nunca ha tenido un período de 20 años con retorno negativo en su historia.</p><div class="summary"><h2>Resumen del Capítulo 18</h2><ul><li>Diversificar entre activos no correlacionados reduce riesgo (Markowitz)</li><li>Clases de activos: acciones (~10%), bonos (~3-5%), REITs (~8-9%), oro (~5-7%)</li><li>Modelos: 60/40, Tres Fondos, All Weather, 100% acciones</li><li>Rebalanceo anual: volver a la asignación objetivo</li><li>Con 20+ años, el S&P 500 nunca ha tenido retorno negativo</li></ul></div>`,
    quiz:{lang:"es",questions:[
      {q:"¿Quién recibió el Nobel en 1990 por la Teoría Moderna de Portafolios?",options:["Warren Buffett","Ray Dalio","Harry Markowitz","Eugene Fama"],answer:2},
      {q:"¿Cuál es el retorno histórico anual aproximado del S&P 500?",options:["5%","7%","~10%","15%"],answer:2},
      {q:"¿En qué consiste la cartera 60/40?",options:["60% bonos + 40% acciones","60% acciones + 40% bonos","60% oro + 40% efectivo","60% real estate + 40% acciones"],answer:1},
      {q:"¿Qué es el rebalanceo de cartera?",options:["Cambiar completamente la estrategia de inversión","Volver a la asignación objetivo vendiendo lo que sobrecreció","Agregar nuevos activos cada año","Reducir el riesgo total cada año"],answer:1},
      {q:"¿Qué clase de activo tiene mayor volatilidad históricamente?",options:["Bonos del Tesoro","Efectivo","Acciones","Oro"],answer:2},
      {q:"¿Cuánto ha rendido históricamente el oro anualmente?",options:["1-2%","5-7%","10-12%","15%"],answer:1},
      {q:"En el All Weather Portfolio de Dalio, ¿qué porcentaje va en acciones?",options:["60%","40%","30%","10%"],answer:2},
      {q:"¿Por qué se recomienda una cartera 100% acciones para inversores jóvenes?",options:["Las acciones nunca bajan","El largo horizonte temporal absorbe la volatilidad","Tienen más conocimiento","Las acciones no pagan impuestos"],answer:1},
      {q:"¿Qué son los REITs?",options:["Bonos del gobierno","Fondos de inversión en bienes raíces","Acciones tecnológicas","Derivados financieros"],answer:1},
      {q:"¿Cuántos períodos de 20 años ha tenido el S&P 500 con retorno negativo?",options:["Ninguno","5","10","Varios en los años 30"],answer:0},
    ]}
  },
  { n:19, file:"MARKETS CAP 19 Impuestos sobre Inversiones ESF.html", title:"Impuestos sobre Inversiones", sub:"Cómo funciona la fiscalidad de las inversiones en EE.UU.: ganancias de capital, dividendos, cuentas con ventajas fiscales y estrategias para optimizar impuestos.",
    body:`<h2>Tipos de Rendimientos Gravables</h2><p>Cuando inviertes, obtienes rendimientos de dos formas, y cada una tiene tratamiento fiscal diferente:</p><table><tr><th>Tipo de Rendimiento</th><th>Qué es</th><th>Cuándo se grava</th></tr><tr><td>Ganancias de capital</td><td>Ganancia al vender un activo por más de lo que costó</td><td>Al vender el activo</td></tr><tr><td>Dividendos</td><td>Distribución de beneficios de la empresa</td><td>Cuando se reciben</td></tr><tr><td>Intereses</td><td>Pago de bonos o cuentas de ahorro</td><td>Cuando se reciben</td></tr></table><h2>Ganancias de Capital: Corto vs. Largo Plazo</h2><div class="highlight-box"><strong>La regla del año:</strong> Si vendes un activo que poseíste menos de 1 año = ganancia de capital a CORTO PLAZO (grava como ingreso ordinario: hasta 37%). Si lo poseíste más de 1 año = ganancia de capital a LARGO PLAZO (0%, 15% o 20% según ingresos).</div><h2>Tasas de Ganancias de Capital Largo Plazo (2026)</h2><table><tr><th>Ingresos Anuales (soltero)</th><th>Tasa Impositiva</th></tr><tr><td>Hasta ~$47,025</td><td>0%</td></tr><tr><td>$47,025 - $518,900</td><td>15%</td></tr><tr><td>Más de $518,900</td><td>20%</td></tr></table><h2>Estrategias de Optimización Fiscal</h2><ul><li><strong>Tax Loss Harvesting</strong>: Vender posiciones con pérdidas para compensar ganancias</li><li><strong>Mantener activos +1 año</strong>: Pasar de tasa ordinaria (hasta 37%) a tasa preferencial (0-20%)</li><li><strong>Maximizar cuentas con ventajas</strong>: 401k, IRA, Roth IRA primero</li><li><strong>Donar activos apreciados</strong>: Evitar el impuesto y recibir deducción caritativa</li></ul><div class="example"><strong>Tax Loss Harvesting en práctica:</strong> Tienes $10,000 de ganancia en Apple. Vendes $10,000 de pérdida en otra posición → Ganancia neta = $0 → Impuesto = $0. Luego recompras una acción similar para mantener la exposición del mercado.</div><div class="summary"><h2>Resumen del Capítulo 19</h2><ul><li>Ganancias corto plazo (&lt;1 año): tributan como ingreso ordinario (hasta 37%)</li><li>Ganancias largo plazo (&gt;1 año): 0%, 15% o 20% según ingresos</li><li>Tax Loss Harvesting: usa pérdidas para compensar ganancias</li><li>Maximizar 401k, IRA y Roth IRA antes de invertir en cuentas gravables</li><li>Mantener activos más de 1 año es una de las estrategias más poderosas</li></ul></div>`,
    quiz:{lang:"es",questions:[
      {q:"¿Cuándo se grava una ganancia de capital?",options:["Cada año aunque no vendas","Solo cuando la empresa paga dividendos","Al vender el activo por más de lo que costó","Cuando el mercado sube un 10%"],answer:2},
      {q:"¿Cuánto tiempo debes mantener un activo para calificar para la tasa preferencial de largo plazo?",options:["6 meses","1 año","2 años","5 años"],answer:1},
      {q:"¿Cuál es la tasa máxima para ganancias de capital a corto plazo?",options:["15%","20%","28%","37%"],answer:3},
      {q:"¿Cuál es la tasa de ganancias de capital largo plazo para ingresos bajos (hasta ~$47k)?",options:["0%","5%","10%","15%"],answer:0},
      {q:"¿Qué es el Tax Loss Harvesting?",options:["Evitar pagar impuestos ilegalmente","Vender posiciones con pérdidas para compensar ganancias gravables","Invertir en bonos libres de impuestos","Reclamar deducciones por inversiones perdidas"],answer:1},
      {q:"¿Cuál es la tasa de ganancias de capital largo plazo para la mayoría de contribuyentes de clase media?",options:["0%","15%","20%","25%"],answer:1},
      {q:"¿Qué tipo de cuenta ofrece ventajas fiscales para la jubilación?",options:["Cuenta corriente","Cuenta de ahorro tradicional","401k, IRA y Roth IRA","Cuenta de margin"],answer:2},
      {q:"¿Cuándo se gravan los dividendos?",options:["Al vender las acciones","Cuando se reinvierten automáticamente","Cuando se reciben","Solo si superan $1,000"],answer:2},
      {q:"Donar activos apreciados a caridad permite:",options:["Solo deducción parcial","Evitar el impuesto sobre la ganancia Y recibir deducción caritativa","Solo evitar el impuesto","Nada; sigues pagando impuestos"],answer:1},
      {q:"¿Qué tipo de ingreso tiene la tasa impositiva más alta en EE.UU.?",options:["Ganancias de capital largo plazo","Dividendos calificados","Ingreso ordinario (incluyendo ganancias corto plazo)","Intereses de bonos municipales"],answer:2},
    ]}
  },
  { n:20, file:"MARKETS CAP 20 El Mercado del Futuro Tendencias 2026-2030 ESF.html", title:"El Mercado del Futuro: Tendencias 2026-2030", sub:"Las grandes fuerzas que moldearán los mercados financieros en los próximos años: IA, tokenización, multipolaridad y nuevas clases de activos.",
    body:`<h2>Tendencia 1: La IA Transforma los Mercados</h2><p>La Inteligencia Artificial está redefiniendo cómo se analizan, negocian y gestionan los activos financieros. Los fondos cuantitativos que usan IA procesan petabytes de datos alternativos — imágenes satelitales de estacionamientos, análisis de sentimiento en redes sociales, registros de transacciones — para tomar decisiones en microsegundos.</p><div class="highlight-box"><strong>Dato 2026:</strong> Más del 80% de las operaciones en los mercados de EE.UU. son ejecutadas por algoritmos. Los fondos que usan IA avanzada superan consistentemente a los gestores humanos en horizontes cortos.</div><h2>Tendencia 2: La Tokenización de Activos</h2><p>La <strong>tokenización</strong> convierte activos reales (bienes raíces, arte, acciones privadas, bonos) en tokens digitales negociables en blockchain. Permite:</p><ul><li>Fraccionar activos ilíquidos (comprar el 0.001% de un edificio)</li><li>Liquidez 24/7 para activos históricamente ilíquidos</li><li>Acceso global sin intermediarios tradicionales</li></ul><div class="example"><strong>BlackRock en 2024:</strong> Lanzó el primer fondo de mercado monetario tokenizado en Ethereum ($BUIDL). En 6 meses superó los $500 millones en activos bajo gestión.</div><h2>Tendencia 3: El Dólar y la Multipolaridad Financiera</h2><p>El dólar representa el 59% de las reservas mundiales (vs 71% en 2001). Los BRICS+ exploran alternativas de pago que no dependan del dólar. La pregunta es si surgirá un serio rival al dólar como moneda de reserva dominante antes de 2030.</p><h2>Tendencia 4: Mercados de Bonos bajo Presión</h2><p>Con deudas globales récord y necesidades de refinanciamiento masivas, los mercados de bonos soberanos enfrentan el desafío de absorber enormes emisiones. La sostenibilidad fiscal de EE.UU., Japón, Italia y el Reino Unido será el tema dominante de los mercados de renta fija hasta 2030.</p><h2>Tendencia 5: La Nueva Arquitectura Financiera</h2><p>DeFi (Finanzas Descentralizadas), stablecoins, CBDCs (monedas digitales de bancos centrales) y plataformas de inversión sin comisiones están democratizando el acceso pero también creando nuevos riesgos regulatorios y sistémicos.</p><div class="summary"><h2>Resumen del Capítulo 20</h2><ul><li>La IA ejecuta el 80%+ de las operaciones en mercados de EE.UU.</li><li>La tokenización permite fraccionar y liquidar activos antes ilíquidos</li><li>El dólar cae del 71% al 59% de reservas mundiales desde 2001</li><li>Las deudas soberanas récord presionarán los mercados de bonos hasta 2030</li><li>DeFi, CBDCs y stablecoins redefinen la arquitectura financiera global</li></ul></div>`,
    quiz:{lang:"es",questions:[
      {q:"¿Qué porcentaje de las operaciones en mercados de EE.UU. ejecutan algoritmos en 2026?",options:["30%","50%","Más del 80%","100%"],answer:2},
      {q:"¿Qué es la tokenización de activos?",options:["Convertir criptomonedas en moneda fiduciaria","Convertir activos reales en tokens digitales en blockchain","Un tipo de ETF","Un derivado financiero"],answer:1},
      {q:"¿Cuál fue el primer fondo tokenizado de BlackRock?",options:["$ETH","$BTC","$BUIDL","$BLKR"],answer:2},
      {q:"¿Qué porcentaje de reservas mundiales representa el dólar en 2026?",options:["71%","65%","59%","50%"],answer:2},
      {q:"¿Cuál era el porcentaje del dólar en reservas mundiales en 2001?",options:["59%","65%","71%","80%"],answer:2},
      {q:"¿Qué permite la tokenización que antes era imposible?",options:["Eliminar todos los impuestos sobre inversiones","Fraccionar activos ilíquidos y darles liquidez 24/7","Invertir sin ningún riesgo","Eliminar los bancos centrales"],answer:1},
      {q:"¿Qué son las CBDCs?",options:["Criptomonedas privadas","Monedas digitales de bancos centrales","Bonos corporativos digitales","ETFs de blockchain"],answer:1},
      {q:"¿Qué tendencia representa el mayor riesgo para los mercados de bonos soberanos hasta 2030?",options:["Tasas de interés muy bajas","Deflación global","Deudas soberanas récord y necesidades masivas de refinanciamiento","Demasiada demanda de bonos"],answer:2},
      {q:"Los fondos cuantitativos con IA usan datos alternativos como:",options:["Solo reportes financieros trimestrales","Imágenes satelitales, sentimiento social y registros de transacciones","Solo noticias económicas","Solo datos históricos de precios"],answer:1},
      {q:"¿Qué buscan los BRICS+ en términos financieros?",options:["Adoptar el dólar como moneda única","Alternativas de pago que no dependan del dólar","Crear un nuevo banco central global","Unirse al sistema SWIFT"],answer:1},
    ]}
  },
];

const dir = "public/content/";
for (const c of caps) {
  const html = makeHTML(`Mercados Financieros · Capítulo ${c.n}`, c.title, c.sub, c.body, c.quiz);
  fs.writeFileSync(dir + c.file, html, "utf8");
  console.log("✓", c.file);
}
console.log("Done mercados");
